gates:
  - id: 1
    source_map: "3"
    source_x: 330
    source_y: 330
    target_map: "0"
    target_x: 100
    target_y: 100
  - id: 2
    source_map: "0"
    source_x: 100
    source_y: 100
    target_map: "3"
    target_x: 330
    target_y: 330
    require_item: true
    required_item_id: 1001
